### ISSUE TITLE
Do we have a staging site set up?

### ISSUE THREAD

**Issue by mfinney** [pwcexc/18f#30]

**Comment by mfinney** [comment]
Could we get it set up to automatically push new files when they are checked in?

**Comment by iaguirre** [comment]
@carlosrodriguez can you post the link to heroku and travis when you get some time?

**Comment by carlosrodriguez** [comment]
Dev site:
http://dev-18f.herokuapp.com/
https://travis-ci.org/pwcexc/18f

**Comment by carlosrodriguez** [comment]
@iaguirre take a look at #31 Once we merge it should start deploying automatically
